CFLAGS=-nostartfiles --entry=main
TARGETS=mips_example intel_x32_example intel_x64_example
TARGETS+=arm32_example aarch64_example
OUTPUT_DIRECTORY=../outputs/
include ../makefiles/generic.mk
all: $(TARGETS)