MIPS_HOST=mips-linux-gnu-
MIPS_CC=$(MIPS_HOST)gcc
MIPS_OBJCOPY=$(MIPS_HOST)objcopy
MIPS_LINKER_SCRIPT=mips.ld

INTEL_HOST=i686-linux-gnu-
X32_CC=$(INTEL_HOST)gcc
X32_OBJCOPY=$(INTEL_HOST)objcopy
X32_LINKER_SCRIPT=i386.ld

X64_CC=$(INTEL_HOST)gcc -m64
X64_OBJCOPY=$(INTEL_HOST)objcopy
X64_LINKER_SCRIPT=i386_64.ld


ARM_HOST=arm-linux-gnueabi-
ARM_CC=$(ARM_HOST)gcc
ARM_OBJCOPY=$(ARM_HOST)objcopy
ARM_LINKER_SCRIPT=arm.ld

AARCH64_HOST=aarch64-linux-gnu-
AARCH64_CC=$(AARCH64_HOST)gcc
AARCH64_OBJCOPY=$(AARCH64_HOST)objcopy
AARCH64_LINKER_SCRIPT=aarch64.ld

RISCV64_HOST=riscv64-linux-gnu-
RISCV64_CC=$(RISCV64_HOST)gcc
RISCV64_OBJCOPY=$(RISCV64_HOST)objcopy
RISCV64_LINKER_SCRIPT=rv64.ld

